Fix C2275 error with latest Visual Studio 2022
This fixes the following build error:

  src\flexasio\FlexASIO\config.cpp(66): error C2275: 'flexasio::`anonymous-namespace'::RemoveOptional<std::optional<int>>::Value': expected an expression instead of a type